/** Even Fibonacci numbers */

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

const fibo = (n, memo = {}) => {
  if (memo[n]) return memo[n]
  if (n === 0) return 1
  if (n === 1) return 2
  return fibo(n - 1) + fibo(n - 2)
}

const getEvenValuedSum = (limit) => {
  let i = 1;
  let memo = {};
  let evenSum = 0;
  let run = true;
  while (run) {
    const currentFibo = fibo(3*i - 2, memo)
    if (currentFibo > limit) run = false
    else evenSum += currentFibo
    i++;
  }
  return evenSum
}

// getEvenValuedSum(10) -> 10 = 2 + 8
// getEvenValuedSum(40) -> 44 = 2 + 8 + 34
